Fix issue with interaction effects
jasp-stats/jaspAnova pull request #43
Opened 2021-05-27 12:23 UTC by vandenman

Fixes https://github.com/jasp-stats/jasp-test-release/issues/1312 and https://forum.cogsci.nl/discussion/7202/bayesian-rm-anova-with-continuous-covariate-posterior-summary-for-interaction#latest

The changes got a bit bigger than I would have liked, but there is a weird issue with Bayesfactor where the column names of the posterior samples are not always the same (hence the need for `jaspBase:::assignFunctionInPackage`).

2021-06-01 10:27 UTC, TimKDJ commented
So I wanted to test this, but I can't run a RM BANOVA:
```
Error in str2lang(x): :1:37: unexpected symbol
1: JaspColumn_.dependent._Encoded ~ RM Factor
                                        ^

Stack trace
doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

AnovaRepeatedMeasuresBayesian(...)

.BANOVArunAnalysis(jaspResults, dataset, options, 'RM-ANOVA')

.BANOVAestimateModels(jaspResults, dataset, options, dataInfo, analysisType)

.BANOVAcreateModelFormula(dependent, modelTerms)

formula(model.formula)

formula.character(model.formula)

str2lang(x)
```

I added `contNormal` and `contGamma` as levels.
I'm on https://github.com/jasp-stats/jasp-desktop/commit/1aae37ad72a110ad9152ffe666ce30cce509e88c. I guess the analysis works ok for you?

2021-06-01 12:05 UTC, vandenman commented
Nope, there is https://github.com/jasp-stats/jasp-test-release/issues/1311

`RM Factor` is not encoded, but it should be encoded.

2021-06-03 10:03 UTC, TimKDJ requested changes
Yup that did the trick.

> there is a weird issue with Bayesfactor where the column names of the posterior samples are not always the same

It's not fully clear to me how the problem manifests itself. Could you elaborate on this further for posterity's sake?

It's always a bit iffy to overwrite functions from other packages, because those functions might change. Do you reckon Richard Morey would incorporate these changes in `BayesFactor` itself?
For now we can include this as the code looks ok, but I do hope it doesn't need to be a permanent fix.

I also ran into a bug which seems to be introduced by this PR:
your anova code <-> current anova code
![RMBANOVA_crash_015](https://user-images.githubusercontent.com/18737241/120626372-e43d6500-c462-11eb-86f6-020b51eff48f.png)

2021-06-22 17:21 UTC, vandenman commented on R/commonAnovaBayesian.R
> +  # identical to BayesFactor::makeChainNeater
Sure, see the example below. In the default BayesFactor output, you **might** get these column names: `subject\r  subject\r  subject\r`. If you do then the analysis fails completely. The "fixed" version ensures that this never happens. I've added a comment to the code + a link to this comment for the future when we'll probably forget why this function exists.
``` r
dd <- structure(list(
  rm_factor = structure(c(1L, 2L, 1L, 2L, 1L, 2L), .Label = c("Level 1", "Level 2"), class = "factor"),
  dependent = c(6, 6, 5, 10, 6, 9),
  age = c(59.2161793866222, 59.2161793866222, 53.4457078686802, 53.4457078686802, 50.3248450015473, 50.3248450015473),
  subject = structure(c(1L, 1L, 2L, 2L, 3L, 3L), .Label = c("1", "2", "3"), class = "factor")),
  row.names = c(NA, 6L), class = "data.frame"
)

bf_obj_1   <- BayesFactor::lmBF(dependent ~ age + subject,             data = dd, whichRandom = "subject")
bf_obj_2   <- BayesFactor::lmBF(dependent ~ age + subject + rm_factor, data = dd, whichRandom = "subject")

head(BayesFactor::posterior(bf_obj_1, iterations = 3)) # <- ugly
#> Markov Chain Monte Carlo (MCMC) output:
#> Start = 1 
#> End = 3 
#> Thinning interval = 1 
#>            mu        age subject\r  subject\r  subject\r     sig2  g_subject
#> [1,] 6.952879  0.1174738 -1.046878  0.8195920  1.6115479 3.994139  5.8023140
#> [2,] 8.031596 -0.1307911 -1.537451 -0.9578494 -2.3139377 6.155536  0.6258592
#> [3,] 6.288544 -0.3799318 -2.279564 -0.3511079 -0.5453107 4.652199 10.6538297
#>      g_continuous
#> [1,]   0.03141617
#> [2,]   0.32068017
#> [3,]   4.30451110
head(BayesFactor::posterior(bf_obj_2, iterations = 3)) # <- good
#> Markov Chain Monte Carlo (MCMC) output:
#> Start = 1 
#> End = 3 
#> Thinning interval = 1 
#>            mu      age-age  subject-1  subject-2  subject-3 rm_factor-Level 1
#> [1,] 6.739169 -0.253795284  1.0040892  1.2774189 -0.7961999        -0.8602879
#> [2,] 7.589073  0.002163719 -2.2805272 -0.4950592 -0.1406161        -0.2574233
#> [3,] 6.556986  0.028899515 -0.5950891  1.6192780  1.2075644        -0.2439207
#>      rm_factor-Level 2     sig2 g_subject g_rm_factor g_continuous
#> [1,]         0.8602879 1.470500 1.3616759  1.16993950    0.1062818
#> [2,]         0.2574233 1.828206 0.5042341  0.06902196    0.1083975
#> [3,]         0.2439207 1.646986 0.5701925  1.65823441    1.3291680

originalFun <- BayesFactor:::makeChainNeater
jaspBase:::assignFunctionInPackage(jaspAnova:::.BANOVAmakeChainNeater, "makeChainNeater", "BayesFactor")
head(BayesFactor::posterior(bf_obj_1, iterations = 3)) # <- good
#> Markov Chain Monte Carlo (MCMC) output:
#> Start = 1 
#> End = 3 
#> Thinning interval = 1 
#>            mu      age-age  subject-1 subject-2  subject-3     sig2 g_subject
#> [1,] 5.358799 -0.114312092  0.8606904  1.431724  1.6816553 2.408533  1.778755
#> [2,] 8.402972 -0.046104769 -3.1759027  1.009812 -1.1468723 2.023300  3.257573
#> [3,] 6.973383 -0.004838664 -0.2433844  3.306020  0.2208826 5.947612  1.412294
#>      g_continuous
#> [1,]    0.2519135
#> [2,]    2.8811262
#> [3,]    1.3659751

jaspBase:::assignFunctionInPackage(originalFun, "makeChainNeater", "BayesFactor")
head(BayesFactor::posterior(bf_obj_1, iterations = 3)) # <- ugly
#> Markov Chain Monte Carlo (MCMC) output:
#> Start = 1 
#> End = 3 
#> Thinning interval = 1 
#>            mu         age subject\r  subject\r subject\r     sig2 g_subject
#> [1,] 6.387079 -0.25497409  1.839726  1.0609555 -0.562025 2.220407 0.9335065
#> [2,] 7.873563  0.23126875 -2.712266 -0.5757739 -1.008893 4.709669 1.9344259
#> [3,] 7.402799  0.09174654  1.343472  0.1753042  1.522370 5.993397 0.4198256
#>      g_continuous
#> [1,]   0.21342648
#> [2,]   0.03393761
#> [3,]   0.21019718
```

<sup>Created on 2021-06-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

2021-06-22 17:42 UTC, vandenman commented
> Do you reckon Richard Morey would incorporate these changes in BayesFactor itself?

I hope so.

I could not replicate the bug you found, but I'll try once more tomorrow (and re-request a review once I'm done).

2021-07-09 13:59 UTC, vandenman commented
Okay so I can't replicate that bug:
![image](https://user-images.githubusercontent.com/21319932/125089211-7bcf4c80-e0ce-11eb-999c-4329a51f58f7.png)

there is an issue with the highlighted `JaspExtraOptions_*_Encoded`. That should be `Level 1` and `Level 2` but I don't know why that is not automatically being decoded. I propose to leave that for a separate issue + PR though, since it may not be caused by the R code.

2021-07-14 11:59 UTC, TimKDJ approved these changes

2021-07-14 11:59 UTC, merged

2021-07-14 12:01 UTC, TimKDJ commented
Do we have issues for the `RM [space] Factor [space] 1` problem and the `JASPExtraOptions_1_Encoded` problem?

2021-07-14 12:35 UTC, vandenman commented
there is https://github.com/jasp-stats/jasp-test-release/issues/1311, but for some reason, it's closed and doesn't seem fixed so I'll reopen it and add the screenshot in there as well.